# Generated by Django 6.1 on 2026-09-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutUs_subheading', models.CharField(blank=True, max_length=800, null=True)),
                ('aboutUs_description', models.CharField(blank=True, max_length=800, null=True)),
                ('aboutUs_banner_image', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
                ('about_purpose_statement', models.CharField(blank=True, max_length=300, null=True)),
                ('about_purpose_body', models.CharField(blank=True, max_length=500, null=True)),
                ('aboutus_vision', models.CharField(blank=True, max_length=500, null=True)),
                ('aboutus_vision_body', models.CharField(blank=True, max_length=500, null=True)),
                ('aboutus_journey', models.CharField(blank=True, max_length=500, null=True)),
                ('aboutus_image', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
            ],
            options={
                'verbose_name': 'About Us Content',
                'verbose_name_plural': 'About Us Content',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Footer & Contact Info',
                'verbose_name_plural': 'Footer & Contact Info',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_text', models.CharField(blank=True, max_length=800, null=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
                ('mission_text', models.CharField(blank=True, max_length=800, null=True)),
                ('mission_image', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
                ('sickle_cell_image', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
                ('poverty_relief_image', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
                ('refugee_support_image', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
                ('aboutus_text', models.CharField(blank=True, max_length=200, null=True)),
                ('aboutus_image', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
                ('get_in_touch_image', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Contents',
            },
        ),
        migrations.CreateModel(
            name='Our_Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_hero_description', models.CharField(blank=True, max_length=500, null=True)),
                ('mission_statement', models.CharField(blank=True, max_length=500, null=True)),
                ('mission_vision', models.CharField(blank=True, max_length=500, null=True)),
                ('mission_gallery_image1', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
                ('mission_gallery_image2', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
                ('mission_gallery_image3', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
            ],
            options={
                'verbose_name': 'Our Mission Content',
                'verbose_name_plural': 'Our Mission Content',
            },
        ),
    ]
