# Generated by Django 6.1 on 2026-08-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=50)),
                ('payment_method', models.CharField()),
                ('stripe_payment', models.CharField(null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
