# Generated by Django 6.1 on 2026-08-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonationPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('F', 'Failed'), ('S', 'Successful')], default='P'),
        ),
    ]
