# Generated by Django 6.1 on 2026-08-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DonationPage', '0002_donation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='stripe_payment',
            new_name='stripe_payment_intent_id',
        ),
    ]
