# Generated by Django 6.1 on 2026-08-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DonationPage', '0003_rename_stripe_payment_donation_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donor_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='payment_method',
        ),
    ]
