# Generated by Django 6.1 on 2026-08-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonationPage', '0006_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemeber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('role', models.CharField(max_length=200)),
            ],
        ),
    ]
