# Generated by Django 6.1 on 2026-09-01 07:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonationPage', '0007_teammemeber'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
