# Generated by Django 6.1 on 2026-09-01 07:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonationPage', '0008_donation_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
