# Generated by Django 6.1 on 2026-09-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonationPage', '0009_alter_donation_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='slug',
        ),
        migrations.AddField(
            model_name='projects',
            name='date_label',
            field=models.CharField(blank=True, help_text='e.g., CHRISTMAS 2026, EASTER 2027, ADVOCACY', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='read_time',
            field=models.CharField(default='5 mins read', help_text='e.g., 5 mins read, Holiday Relief, Patient Voice', max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Target launch or execution date', null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('U', 'UPCOMING'), ('A', 'ACTIVE')], default='UPCOMING'),
        ),
    ]
