# Generated by Django 6.1 on 2026-09-01 19:44

import partial_date.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonationPage', '0010_remove_projects_slug_projects_date_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='scheduled_date',
            field=partial_date.fields.PartialDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'UPCOMING'), ('ACTIVE', 'ACTIVE')], default='UPCOMING'),
        ),
    ]
