# Generated by Django 6.1 on 2026-09-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonationPage', '0011_alter_projects_scheduled_date_alter_projects_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='scheduled_date',
            field=models.CharField(blank=True, help_text='e.g., CHRISTMAS 2026, EASTER 2027, ADVOCACY', max_length=50, null=True),
        ),
    ]
