# Generated by Django 5.2.17 on 2026-09-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonationPage', '0013_alter_contactform_id_alter_donation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='stripe_payment_intent_id',
        ),
        migrations.AddField(
            model_name='donation',
            name='sumup_checkout_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
